### ISSUE TITLE
Init new plugin

### ISSUE THREAD

**Issue by boardmain** [GrapesJS/cli#282]
when i try to init the project
i have this error

/Volumes/SSDInternal/Node/editorgrapejs/samplePlugin/node_modules/path-scurry/node_modules/lru-cache/dist/cjs/index.js:52
            this.signal.onabort?.(reason);
                                ^

SyntaxError: Invalid or unexpected token
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

( node 18.16.0 , macos )

**Comment by gankairen** [comment]
I had this problem also, and edited that particular file myself in order to fix. In your case, you need to edit /Volumes/SSDInternal/Node/editorgrapejs/samplePlugin/node_modules/path-scurry/node_modules/lru-cache/dist/cjs/index.js

Do a find/replace for the following in the order shown here:
- "?.(" to "("
- "?." to "."

Then save the file with the changes and then run the command again.

**Comment by artf** [comment]
Published a new [release](https://github.com/GrapesJS/cli/releases/tag/v4.1.0) that should fix that issue
